import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font, Image } from '@react-pdf/renderer';

// Register fonts if needed (using default for now)
const styles = StyleSheet.create({
  page: { 
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff'
  },
  coverHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: '#0f382c',
    padding: 30,
    borderBottom: '8px solid #facc15',
    marginBottom: 30
  },
  qrCode: {
    width: 60,
    height: 60,
    padding: 3,
    backgroundColor: '#ffffff',
    borderRadius: 2
  },
  title: {
    fontSize: 20,
    fontWeight: 'extrabold',
    color: '#ffffff',
    textTransform: 'uppercase',
    marginBottom: 4
  },
  subtitle: {
    fontSize: 9,
    fontWeight: 'bold',
    color: 'rgba(255,255,255,0.7)',
    textTransform: 'uppercase'
  },
  contentContainer: {
    paddingHorizontal: 40
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'extrabold',
    color: '#022c22',
    textTransform: 'uppercase',
    marginBottom: 10,
    marginTop: 20,
    borderLeft: '4px solid #10b981',
    paddingLeft: 8
  },
  table: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    border: '2px solid #022c22',
    marginBottom: 20
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1px solid #022c22'
  },
  tableColHeader: {
    width: '40%',
    backgroundColor: '#ecfdf5',
    padding: 8,
    borderRight: '1px solid #022c22',
    fontSize: 10,
    fontWeight: 'bold',
    color: '#022c22'
  },
  tableCol: {
    width: '60%',
    padding: 8,
    fontSize: 10
  },
  pageHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#022c22',
    marginBottom: 20,
    borderBottom: '2px solid #022c22',
    paddingBottom: 10,
    textTransform: 'uppercase'
  },
  chunk: {
    padding: 10,
    marginBottom: 15,
    borderLeft: '4px solid #000'
  },
  compliantChunk: {
    borderLeftColor: '#10b981',
    backgroundColor: '#ecfdf5'
  },
  mediumChunk: {
    borderLeftColor: '#f59e0b',
    backgroundColor: '#fef3c7'
  },
  highChunk: {
    borderLeftColor: '#ef4444',
    backgroundColor: '#fee2e2'
  },
  paragraph: {
    fontSize: 10,
    lineHeight: 1.5,
    color: '#1f2937'
  },
  explanationNote: {
    fontSize: 9,
    color: '#991b1b',
    marginTop: 8,
    backgroundColor: '#ffffff',
    padding: 6,
    border: '1px solid #fca5a5'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9ca3af',
    borderTop: '1px solid #022c22',
    paddingTop: 10,
    textAlign: 'justify'
  }
});

interface PDFReportTemplateProps {
  data: any;
  userName: string;
  userEmail: string;
}

export const PDFReportTemplate = ({ data, userName, userEmail }: PDFReportTemplateProps) => {
  if (!data) return null;

  // Parse document JSON strictly mapping over the new Pages -> Chunks structure
  const parsedDoc = data.parsedDocumentJson ? JSON.parse(data.parsedDocumentJson) : { pages: [] };
  const pages = parsedDoc.pages || [];

  // Calculate statistics
  let totalChunks = 0;
  let compliantCount = 0;
  let mediumCount = 0;
  let highCount = 0;

  pages.forEach((page: any) => {
    page.chunks.forEach((chunk: any) => {
      totalChunks++;
      if (chunk.status === 'HIGH_RISK' || chunk.status === 'high') highCount++;
      else if (chunk.status === 'MEDIUM_RISK' || chunk.status === 'medium') mediumCount++;
      else compliantCount++;
    });
  });

  const compliantPct = totalChunks > 0 ? Math.round((compliantCount / totalChunks) * 100) : 0;
  const mediumPct = totalChunks > 0 ? Math.round((mediumCount / totalChunks) * 100) : 0;
  const highPct = totalChunks > 0 ? Math.round((highCount / totalChunks) * 100) : 0;

  const getHighlightStyle = (status: string) => {
    const s = status?.toUpperCase();
    if (s === 'HIGH_RISK' || s === 'HIGH') return [styles.chunk, styles.highChunk];
    if (s === 'MEDIUM_RISK' || s === 'MEDIUM') return [styles.chunk, styles.mediumChunk];
    return [styles.chunk, styles.compliantChunk];
  };

  return (
    <Document>
      {/* PAGE 1: COVER PAGE */}
      <Page size="A4" style={styles.page}>
        <View style={styles.coverHeader}>
          <View style={{ flex: 1 }}>
            <Text style={styles.title}>OzikSustain Verification Report</Text>
            <Text style={styles.subtitle}>SHA-256 AUDIT ID: {data.sha256Hash?.substring(0,16) || data.auditId?.substring(0,16) || "N/A"}...</Text>
            <Text style={{ fontSize: 8, color: 'rgba(255,255,255,0.5)', marginTop: 8, fontStyle: 'italic' }}>The Report is Generated by OzikSustain AI Compliance & Legal Audit Engine (Pasal.id Integrated)</Text>
          </View>
          <View>
            <Image 
              src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(`https://oziksustain.vercel.app/verify/${data.sha256Hash || data.auditId}`)}`} 
              style={styles.qrCode} 
            />
          </View>
        </View>

        <View style={styles.contentContainer}>
          <Text style={styles.sectionTitle}>01. Submission Information</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Project Name</Text>
            <Text style={styles.tableCol}>{data.projectName || "Unnamed Project"}</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Author / Submitter</Text>
            <Text style={styles.tableCol}>{userName} ({userEmail})</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Submission Date</Text>
            <Text style={styles.tableCol}>{new Date(data.createdAt || Date.now()).toLocaleDateString('id-ID')}</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Feasibility Score</Text>
            <Text style={[styles.tableCol, { fontWeight: 'bold' }]}>{data.feasibilityScore}/100</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Document Metadata</Text>
            <Text style={styles.tableCol}>{data.totalPages} Pages • {data.totalSentences} Sentences</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>02. Content Composition</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Compliant Clauses</Text>
            <Text style={styles.tableCol}>{compliantPct}% ({compliantCount})</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Medium Risk</Text>
            <Text style={styles.tableCol}>{mediumPct}% ({mediumCount})</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>High Risk Violations</Text>
            <Text style={styles.tableCol}>{highPct}% ({highCount})</Text>
          </View>
        </View>
        
        <Text style={styles.sectionTitle}>03. 4-Pillar Scoring Breakdown</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Legal Compliance (Max 40)</Text>
            <Text style={styles.tableCol}>{data.scoreLegal || 0}</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Technical (Max 30)</Text>
            <Text style={styles.tableCol}>{data.scoreTechnical || 0}</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Social (Max 15)</Text>
            <Text style={styles.tableCol}>{data.scoreSocial || 0}</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.tableColHeader}>Transparency (Max 15)</Text>
            <Text style={styles.tableCol}>{data.scoreTransparency || 0}</Text>
          </View>
        </View>

        </View>
        <Text style={styles.footer}>
          This report was automatically generated by the OzikSustain AI Engine. The feasibility score and risk analysis are calculated algorithmically based on cross-referencing user-submitted text against the Pasal.id spatial and legal datasets (Permen ESDM, UU LHK, etc.). This document does not constitute formal legal advice. Document ID: {data.sha256Hash || data.auditId}
        </Text>
      </Page>

      {/* PAGE 2+: DOCUMENT CONTENT */}
      {pages.map((page: any, pageIndex: number) => (
        <Page key={`page-${pageIndex}`} size="A4" style={[styles.page, { padding: 40 }]}>
          <Text style={styles.pageHeader}>DOCUMENT ANALYSIS - Page {page.page_number}</Text>
          
          {page.chunks?.map((chunk: any, chunkIndex: number) => (
            <View key={`chunk-${chunk.id || chunkIndex}`} style={getHighlightStyle(chunk.status)}>
              <Text style={styles.paragraph}>{chunk.text}</Text>
              
              {/* Inline Annotation for Non-Compliant */}
              {(chunk.status?.toUpperCase() === 'HIGH_RISK' || chunk.status?.toUpperCase() === 'HIGH' || chunk.status?.toUpperCase() === 'MEDIUM_RISK' || chunk.status?.toUpperCase() === 'MEDIUM') && chunk.issue && (
                <View style={styles.explanationNote}>
                  <Text style={{ fontWeight: 'bold', marginBottom: 2 }}>Citation: {chunk.issue.matchedLaw || chunk.issue.MatchedLaw}</Text>
                  <Text style={{ fontStyle: 'italic', marginBottom: 2 }}>"{chunk.issue.originalLawText || chunk.issue.OriginalLawText}"</Text>
                  <Text style={{ color: '#047857', fontWeight: 'bold' }}>Suggestion: {chunk.issue.suggestedRevision || chunk.issue.SuggestedRevision}</Text>
                </View>
              )}
            </View>
          ))}
          
          <Text style={styles.footer}>
            OzikSustain Confidential • Page {pageIndex + 2}
          </Text>
        </Page>
      ))}
    </Document>
  );
};
